<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/29
 * Time: 12:31
 */
namespace Admini\Controller;


use Think\Model;

class ContainerTypeController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 容器类型列表
     * */
    public function index(){

        if(I('get.action')!='getListAjax'){
            $this->CheckAuth();
            $this->display();
        }else{
            $this->getContainerTypeAjax();
            die();
        }
    }
    /**
     * 获取容器类型
     * */
    private function getContainerTypeAjax(){

        $page = I('pageNumber');//页码
        $rows =  I('pageSize');//条数
        $sortName = I('sortName');
        $sortOrder =  I('sortOrder');
        $address = I('address');
        $condition = '';
        if($address>0){
            $condition .= " and equipment_address = ".$address;
        }
        $sql = D('container_type');
        $row = $sql->getList($page,$rows,$condition,$sortName,$sortOrder);

        $data['data']['total']=$row['total'];
        $data['data']['rows']=$row['rows'];
        $data['success']=200;
        $data['message']=null;
        echo json_encode($data);die;
//        if($row['rows']){
//            $data['data']['total']=$row['total'];
//            $data['data']['rows']=$row['rows'];
//            $data['success']=200;
//            $data['message']=null;
//        }else{
//            $data['success']=400;
//            $data['message']="暂无数据!";
//        }

    }

    /**
     * 编辑
     * */
    public function editContainerType(){

        if(!$this->CheckAuth(true,"Admini/ContainerType/editContainerType")){
            $result['code']=400;
            $result['msg']='没有使用该功能的权限！';
            $this->ajaxReturn($result);
            die;
        }
        if(I('get.act')=='display'){
            $id = $_POST['id'];
            if(empty($id)) {
                echo json_encode( array('code'=>400,'msg'=>'请选择数据!'));die();
            }
            $sql = D('container_type');
            $rs = $sql -> getOne($id);
            $data = $rs !== false ? array('code'=>200,'row'=>$rs) : array('code'=>400,'msg'=>'暂无数据!');
            echo json_encode($data);die();
        }else if(I('get.act')=='submit'){
            $id = $_POST['id'];
            $from = I('post.from');
            $facility = D('container_type');
            $data['is_del'] = trim($from['is_del']);
            $data['name'] = trim($from['name']);
            $data['longs'] = trim($from['longs']);
            $data['wide'] = trim($from['wide']);
            $data['higt'] = trim($from['higt']);
            $data['capacity'] = trim($from['capacity']);
            foreach ($data as $k=>$v){
                if(empty($v)) {
                    $rs['code'] = 400;
                    $rs['msg'] = '请完善数据!';
                    echo json_encode($rs);die;
                }
            }
            if(I('get.action')=='edit'){
                $row = $facility->where('id = '.$id)->save($data);
                unset($data);
                if($row!==false){
                    $data['code'] = 200;
                    $data['msg'] = '修改成功!';
                    $log = "{$_SESSION['admin']['account']}修改了设备ID为[$id]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '修改失败!';
                }
            }else if(I('get.action')=='add'){
                $data['createtime'] = time();
                $row = $facility->data($data)->add();
                unset($data);
                if($row!==false){
                    $data['code'] = 200;
                    $data['msg'] = '添加成功!';
                    $log = "{$_SESSION['admin']['account']}添加了设备ID为[{$facility->getLastInsID()}]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '添加失败!';
                }
            }else if(I('get.action')=='del'){
                $id = I('post.id','','trim');
                $row = $facility->where('id = '.$id)->delete();
                if($row !==false){
                    $data['code'] = 200;
                    $data['msg'] = '删除成功!';
                    $log = "{$_SESSION['admin']['account']}删除了设备ID为[{$id}]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '删除失败!';
                }

            }else{
                die('非法操作！');
            }
            echo json_encode($data);
            die();
        }else{
            die('非法操作！');
        }
    }

}