<?php
/**
 * Created by PhpStorm.
 * User: yara
 * Date: 2017/5/17
 * Time: 11:44
 */
namespace Admini\Controller;


use Think\Model;

class FacilityController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 设备列表
     * */
    public function facilityList(){

        if(I('get.action')!='getListAjax'){
            $this->CheckAuth();
            $this->display();
        }else{
            $this->getFacilityAjax();
            die();
        }
    }
    /**
     * 设备列表
     * */
    private function getFacilityAjax(){

        $page = I('pageNumber');//页码
        $rows =  I('pageSize');//条数
        $sortName = I('sortName');
        $sortOrder =  I('sortOrder');
        $address = I('address');
        $condition = '';
        if($address>0){
            $condition .= " and equipment_address = ".$address;
        }
        $sql = D('equipment_list');
        $row = $sql->getList($page,$rows,$condition,$sortName,$sortOrder);

        $data['data']['total']=$row['total'];
        $data['data']['rows']=$row['rows'];
        $data['success']=200;
        $data['message']=null;
        echo json_encode($data);die;
//        if($row['rows']){
//            $data['data']['total']=$row['total'];
//            $data['data']['rows']=$row['rows'];
//            $data['success']=200;
//            $data['message']=null;
//        }else{
//            $data['success']=400;
//            $data['message']="暂无数据!";
//        }

    }

    /**
     * 编辑设备
     * */
    public function editFacility(){

        if(!$this->CheckAuth(true,"Admini/Facility/editFacility")){
            $result['code']=400;
            $result['msg']='没有使用该功能的权限！';
            $this->ajaxReturn($result);
            die;
        }
        if(I('get.act')=='display'){
            $id = $_POST['id'];
            if(empty($id)) {
                echo json_encode( array('code'=>400,'msg'=>'请选择数据!'));die();
            }
            $sql = D('equipment_list');
            $rs = $sql -> getOne($id);
            $data = $rs !== false ? array('code'=>200,'row'=>$rs) : array('code'=>400,'msg'=>'暂无数据!');
            echo json_encode($data);die();
        }else if(I('get.act')=='submit'){
            $id = $_POST['id'];
            $from = I('post.from');
            $data['equipment_address'] = strval(trim($from['equipment_address']));
            $facility = D('equipment_list');
            if(I('get.action')=='add'||(I('get.action')=='edit'&&$from['hidden_equipment_address']!=$data['equipment_address'])){
                $row_serialnumber = $facility->where('equipment_address = '.$data['equipment_address'])->find();
                if($row_serialnumber !=false) {echo json_encode(array('code'=>400,'msg'=>'装置地址已存在！'));die();}
            }
            $data['is_del'] = trim($from['is_del']);

            if(I('get.action')=='edit'){
                $row = $facility->where('id = '.$id)->save($data);
                unset($data);
                if($row!==false){
                    $data['code'] = 200;
                    $data['msg'] = '修改成功!';
                    $log = "{$_SESSION['admin']['account']}修改了设备ID为[$id]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '修改失败!';
                }
            }else if(I('get.action')=='add'){
                $data['createtime'] = time();
                $row = $facility->data($data)->add();
                unset($data);
                if($row!==false){
                    $data['code'] = 200;
                    $data['msg'] = '添加成功!';
                    $log = "{$_SESSION['admin']['account']}添加了设备ID为[{$facility->getLastInsID()}]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '添加失败!';
                }
            }else if(I('get.action')=='del'){
                $id = I('post.id','','trim');
                $row = $facility->where('id = '.$id)->delete();
                if($row !==false){
                    $data['code'] = 200;
                    $data['msg'] = '删除成功!';
                    $log = "{$_SESSION['admin']['account']}删除了设备ID为[{$id}]的信息。";
                    $this->writelog("equipment",$log);
                }else{
                    $data['code'] = 400;
                    $data['msg'] = '删除失败!';
                }

            }else{
                die('非法操作！');
            }
            echo json_encode($data);
            die();
        }else{
            die('非法操作！');
        }
    }



    /**
     * 异步加载首页运行设备地图
     * */
    public function getOperationFacility(){
        if(!$this->CheckAuth(true,"Admini/Index/getOperationFacility")){
            $result['code']=400;
            $result['msg']='没有使用该功能的权限！';
            $this->ajaxReturn($result);
            die;
        }
        $facility = D('facilities');
        $row = $facility->getMainFacility($this->table,I('post.is_run','','trim'));
        $data = $row['row']!==false ? array('code'=>200,'row'=>$row['row'],'nums'=>$row['nums']) : array('code'=>400,'msg'=>'暂无数据!');
        echo json_encode($data);
    }

    /**
     * 异步加载全国故障设备地图
     * */
    public function getFaultFacility(){
        if(!$this->CheckAuth(true,"Admini/Index/getFaultFacility")){
            $result['code']=400;
            $result['msg']='没有使用该功能的权限！';
            $this->ajaxReturn($result);
            die;
        }
        $facility = D('facilities');
        $row = $facility->getMainFacility($this->table,I('post.is_run','','trim'));
        $data = $row['row']!==false ? array('code'=>200,'row'=>$row['row'],'nums'=>$row['nums']) : array('code'=>400,'msg'=>'暂无数据!');
        echo json_encode($data);
    }

    /**
     * 设备历史状态列表
     * */
    public function historyStatus(){
        for($i=1;$i<1001;$i++){
            $data[$i-1]['number'] = str_pad($i,6,0,STR_PAD_LEFT);
        }
//        echo '<pre>';
//        var_dump($data);die();
//        $this->addAll($data);
        if(!$this->CheckAuth(true,"Admini/Index/historyStatus")){
            $result['code']=400;
            $result['msg']='没有使用该功能的权限！';
            $this->ajaxReturn($result);
            die;
        }
        $facilities = D('facilities');
        if(!empty($_POST['minute'])){
            $facilities->minute();
        }
        $fid = array(
            0 => I('get.fid','','trim')
        );
        $times[0] = !empty($_GET['addtime_s']) ? strtotime(I('get.addtime_s','','trim')) : '';
        $times[1] = !empty($_GET['addtime_e']) ? strtotime(I('get.addtime_e','','trim')) : '';

        $row = $facilities->historyList($fid,array(),$times);
        $data_set['data']['total']=$row['total'];
        $data_set['data']['rows']=$row['row'];
        $data_set['sum_up'] = $row['sum_up'];
        $data_set['success']=200;
        $data_set['message']=null;

        echo json_encode($data_set);die();
    }

//    public function ceshi(){
//        echo "<pre>";
//        var_dump($_POST);die();
//    }

}