<?php
/**
 * Created by PhpStorm.
 * User: yara
 * Date: 2017/5/15
 * Time: 16:14
 */
namespace Admini\Controller;


use Think\Model;

class RoleController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * AJAX获取角色列表
     * */
    public function getRoleAjax(){
        $role = M('auth_group');
        $row = $role->where('status = 1')->select();
        $data = $row!==false ? $this->returnArr() : $this->returnArr(400,'暂无数据!');
        $data['row'] = $row;
        $data['num'] = count($row);
        echo json_encode($data);die();
    }
}