<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/30
 * Time: 12:10
 */
namespace Admini\Controller;


use Think\Model;

class StatisticsController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //统计页面
    public function index(){
        $this->CheckAuth();
        if(I('get.action')!='getListAjax'){
            $this->display();
        }else{
            $this->getFacilityAjax();
            die();
        }
    }

}